models/reservations/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for, json
from models.reservations import ReservationWeb
from models.payment_information.payment_service import PaymentService
from models.forms.forms import CreateReservationPage1Form, CreateReservationPage2Form, AddPaymentInformationForm, \
    DeleteReservation, ConfirmReservationForm, UpdateWhichReservation, UpdateReservationDates, UpdateConfirm, \
    ProvideFeedback, ViewFeedbackChooseLocation, ReviewReservationForm, DeletePaymentInformationForm
from application import login_manager
from flask_login import login_required
from flask_login import current_user
from datetime import datetime
from datetime import timedelta
from datetime import date
import uuid
from models.rooms import room_service

reservation_home_page_app = Blueprint('reservation_home_page_app', __name__)
reservationweb = ReservationWeb()
payment_service = PaymentService()
roomservice = room_service.RoomService()


@reservation_home_page_app.route('/create-reservation', methods=['GET', 'POST'])
@login_required
def create_reservation():
    form = CreateReservationPage1Form(request.form)
    error = None
    location_list = reservationweb.get_locations()
    form.location.choices = [(location, location) for location in location_list]
    if request.method == 'POST':
        location = request.form.get('location')
        start_date = request.form.get('stdt')
        end_date = request.form.get('enddt')
        if start_date == '' or end_date == '':
            error = "You cannot leave the date fields blank"
        else:
            start_date = str(start_date)
            end_date = str(end_date)
            session['loc'] = location
            session['s_date'] = start_date
            session['e_date'] = end_date
            available_reservations = reservationweb.check_for_rooms(start_date, end_date, location)
            # add serialization: session['available_rooms'] = available_reservations
            if not available_reservations:
                error = "There are no available rooms that match your criteria"
            elif datetime.strptime(start_date, "%Y-%m-%d").date() <= date.today():
                error = "You must choose a date in the future"
            elif datetime.strptime(start_date, "%Y-%m-%d").date() >= datetime.strptime(end_date, "%Y-%m-%d").date():
                error = "You must choose a checkout date after the check in date"
            else:
                return redirect('/create-reservation-2')
    return render_template('create_reservation/create_reservation_page1.html', form=form, error=error)


@reservation_home_page_app.route('/create-reservation-2', methods=['GET', 'POST'])
@login_required
def create_reservation_page2():
    error = None
    all_selected_rooms_list = []
    start_date = session['s_date']
    end_date = session['e_date']
    location = session['loc']
    available_rooms = reservationweb.check_for_rooms(start_date, end_date, location)
    # s_rooms = available_rooms.__dict__
    # print s_rooms
    size = len(available_rooms)
    form = CreateReservationPage2Form(request.form)
    i = 0
    if request.method == 'POST':
        # rooms_selected = request.form.get('customer_room')
        rooms_selected = request.form.getlist('check')
        if len(rooms_selected) == 0:
            error = "You must select at least one room"
        else:
            for rs in rooms_selected:
                for room in available_rooms:
                    if rs == str(room.room_num):
                        # room_categories_numbers = {"room_number": room.room_num, "room_category": room.category}
                        all_selected_rooms = {'room_number': room.get_room_num(), 'category': room.get_category(),
                                              'persons_allowed': room.get_num_people(), 'cost_per_day': room.get_cost(),
                                              'cost_extra_bed': room.get_cost_extra_bed(), 'extra_bed': 0}
                        all_selected_rooms_list.append(all_selected_rooms)
            session['rooms'] = all_selected_rooms_list
            session['reservation_id'] = uuid.uuid4()
            return redirect(url_for('reservation_home_page_app.confirm_reservation'))
    return render_template('create_reservation/create_reservation_page2.html', form=form,
                           available_rooms=available_rooms,
                           location=location, error=error)


@reservation_home_page_app.route('/confirm-reservation', methods=['GET', 'POST'])
@login_required
def confirm_reservation():
    rooms = session['rooms']
    extra_beds_room_numbers = []
    form = ConfirmReservationForm(request.form)
    if request.method == 'POST':
        extra_beds = request.form.getlist('check')
        for bed in extra_beds:
            extra_beds_room_numbers.append(int(bed))
        i = 0
        j = 0
        while i < len(extra_beds_room_numbers):
            if extra_beds_room_numbers[i] == rooms[j]['room_number']:
                rooms[j]['extra_bed'] = 1
                j = 0
                i += 1
            else:
                j += 1
        if len(extra_beds_room_numbers) > 0:
            session['rooms'] = rooms
        return redirect(url_for('reservation_home_page_app.review_reservation'))
    return render_template('create_reservation/confirm_reservation.html', form=form, rooms=rooms)


@reservation_home_page_app.route('/review_reservation', methods=['GET', 'POST'])
@login_required
def review_reservation():
    error = None
    start_date = session['s_date']
    end_date = session['e_date']
    location = session['loc']
    rooms = session['rooms']
    reservation_id = session['reservation_id']
    credit_cards = payment_service.get_payment_information_by_username(current_user)
    form = ReviewReservationForm(request.form)
    form.credit_card.choices = [(cc.get_card_number(), cc.get_card_number()) for cc in credit_cards]
    total_cost = reservationweb.get_total_cost(rooms, start_date, end_date)
    print rooms
    if request.method == 'POST':
        credit_card_to_use = request.form.get('credit_card')
        if credit_card_to_use is None:
            error = "You must select or add a credit card"
        else:
            reservationweb.create(reservation_id, current_user, location, start_date, end_date, credit_card_to_use, rooms)
            return redirect('/')
    return render_template('create_reservation/review_reservation.html', form=form, reservation_id=reservation_id,
                           start_date=start_date, end_date=end_date, location=location, total_cost=total_cost,
                           rooms=rooms, error=error)


@reservation_home_page_app.route('/add-credit-card', methods=['GET', 'POST'])
@login_required
def add_credit_card():
    error = None
    form = AddPaymentInformationForm(request.form)
    if request.method == 'POST':
        card_number = request.form.get('card_number')
        card_exists = reservationweb.check_credit_card(card_number)
        name = request.form.get('name')
        expiration_date = request.form.get('expiration_date')
        cvv = request.form.get('cvv')
        if card_number == '' or name == '' or expiration_date == '' or cvv == '':
            error = "All fields must be completed"
        else:
            if card_exists is True:
                error = "The card number you have entered already exists."
            else:
                reservationweb.add_credit_card(name, card_number, expiration_date, cvv, current_user)
                return redirect(url_for('reservation_home_page_app.review_reservation'))
    return render_template('user/add_credit_card.html', form=form, error=error)


@reservation_home_page_app.route('/delete-credit-card', methods=['GET', 'POST'])
@login_required
def delete_credit_card():
    error = None
    form = DeletePaymentInformationForm(request.form)
    credit_cards = payment_service.get_payment_information_by_username(current_user)
    form.credit_card.choices = [(cc.get_card_number(), cc.get_card_number()) for cc in credit_cards]
    if request.method == 'POST':
        card_number = request.form.get('credit_card')
        can_delete = reservationweb.check_to_delete_credit_card(card_number)
        if can_delete is True:
            reservationweb.delete_credit_card(card_number)
            return redirect(url_for('reservation_home_page_app.review_reservation'))
        else:
            error = "You cannot delete a card that is being used by a reservation"
    return render_template('user/delete_credit_card.html', form=form, error=error)


@reservation_home_page_app.route('/customerreservationhome')
@login_required
def customer_home():
    reservations = reservationweb.get_reservations_by_username(current_user)
    return render_template('view_reservation/view_reservation.html', reservation_list=reservations)


@reservation_home_page_app.route('/delete-reservation', methods=['GET', 'POST', 'DELETE'])
@login_required
def delete_reservation():
    error = None
    message = None
    reservation_list = reservationweb.get_future_reservations(current_user)
    form = DeleteReservation(request.form)
    if request.method == 'POST':
        reservation_to_delete = request.form.getlist('reservation')
        if len(reservation_to_delete) > 1:
            error = "You can only select one reservation to delete"
        elif len(reservation_to_delete) == 0:
            error = "You must select a reservation to delete. If none are displayed, you do not have any reservations."
        elif len(reservation_to_delete) == 1:
            reservation_to_delete = reservation_to_delete[0]
            reservation = reservationweb.get_reservation_by_reservation_id(str(reservation_to_delete))
            if datetime.strptime(reservation.start_date, "%Y-%m-%d").date() <= date.today() + timedelta(days=1):
                message = "You have successfully deleted your reservation and will receive a 0% refund of $0"

templates/create_reservation/cancel_reservation.html
{% extends "index/index.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/style.css">
{% endblock %}

{% block content %}

    <div class="container user-index-padding">
        {% if error %}
            <h5 style="color:red;">Error: {{ error }} </h5>
        {% endif %}
        <form action="" method="post" name="deleteReservation">
                {{ form.hidden_tag }}
                <div class="form-group ">

                </div>
                <div class="row">
                    <h4 class="col-md-2 text-left">Delete Reservation:</h4>
                </div>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th>ReservationID</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Location</th>
                <th>Choose Reservation</th>
            </tr>
            {% for reservation in reservation_list %}
                <tr>
                    <td>{{ reservation.reservation_id }}</td>
                    <td>{{ reservation.start_date }}</td>
                    <td>{{ reservation.end_date }}</td>
                    <td>{{ reservation.hotel_location }}</td>
                    <td>{{ form.reservation(value=reservation.reservation_id) }}</td>
                </tr>
            {% endfor %}
        </table>
            {{ form.submit(class_="btn btn-default right-align") }}
        </form>
    </div>
{% endblock %}

templates/create_reservation/confirm_reservation.html
{% extends "index/index.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/style.css">
{% endblock %}

{% block content %}

    <div class="container user-index-padding">
        <div class="row">
            {% if error %}
                <h5 style="color:red;">Error: {{ error }} </h5>
            {% endif %}
        </div>
        <form action="" method="post" name="deleteReservation">
        {{ form.hidden_tag }}
        <div class="row">
            <table class="table table-striped table-bordered table-condensed">
                <tr>
                    <th>Room Number</th>
                    <th>Room Category</th>
                    <th># Persons Allowed</th>
                    <th>Cost Per Day</th>
                    <th>Cost of Extra Bed Per Day</th>
                    <th>Extra Bed?</th>
                </tr>
                {% for room in rooms %}
                    <tr>
                        <td>{{ room['room_number'] }}</td>
                        <td>{{ room['category'] }}</td>
                        <td>{{ room['persons_allowed'] }}</td>
                        <td>{{ room['cost_per_day'] }}</td>
                        <td>{{ room['cost_extra_bed']}}</td>
                        <td>{{ form.check(value=room.room_number) }}</td>

                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="row">
            <div class="form-group row">
                <div class="text-left col-md-2">
                    {{ form.next_page(class_="btn btn-default right-align") }}
                </div>
            </div>
        </div>

        </form>
    </div>
{% endblock %}

templates/create_reservation/create_reservation_page1.html
{% extends "index/index.html" %}
{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
    <div class="jumbotron">
    {% if error %}
        <h5 style="color:red;">Error: {{ error }} </h5>
    {% endif %}
    <h1>Search Rooms</h1>
        <form action="" method="post" name="createReservation">
                {{ form.hidden_tag }}
                <div class="form-group ">

                </div>
                <div class="form-group row">
                    <h4 class="col-md-2 text-left">Location</h4>
                    <div class="text-left col-md-6">
                        {{ form.location(class_="form-control") }}
                    </div>
                </div>
            <div class="row">
                <div class="form-group text-left col-md-6">
                    <h4>Start Date</h4>
                        {{ form.stdt(type = 'date',class='datepicker') }}
                </div>
                <div class="form-group text-left col-md-6">
                    <h4>Checkout Date</h4>
                        {{ form.enddt(type = 'date',class='datepicker') }}
                </div>
            </div>
                {{ form.search(class_="btn btn-default right-align") }}
        </form>
    </div>

{% endblock %}

templates/create_reservation/review_reservation.html
{% extends "index/index.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/style.css">
{% endblock %}

{% block content %}

    <div class="container user-index-padding">
    <form action="" method="post" name="deleteReservation">
        {% if error %}
            <h5 style="color:red;">Error: {{ error }} </h5>
        {% endif %}

        {{ form.hidden_tag }}
        <div class="row">
            <h3>Review and Payment</h3>
            <table class="table table-striped table-bordered table-condensed">
                <tr>
                    <th>ReservationID</th>
                    <td>>{{ reservation_id }}</td>
                </tr>
                <tr>
                    <th>Start Date:</th>
                    <td>{{ start_date }}</td>
                </tr>
                <tr>
                    <th>End Date:</th>
                    <td>{{ end_date }}</td>
                </tr>
                <tr>
                    <th>Location:</th>
                    <td>{{ location }}</td>
                </tr>
                <tr>
                    <th>Total Cost:</th>
                    <td>${{ total_cost }}</td>
                </tr>
            </table>
            <h4>Rooms:</h4>
            <table class="table table-striped table-bordered table-condensed">
                <th>Room Number:</th>
                <th>Room Category:</th>
                <th>Extra Bed:</th>
                <th>Cost per Night</th>
                <th>Cost per Extra Bed</th>
                <th>Total Room Cost Per Night</th>
                {% for room in rooms %}
                    <tr>
                        <td>>{{ room['room_number'] }}</td>
                        <td>{{ room['category'] }}</td>
                        {% if room['extra_bed'] == 1 %}
                            <td>Yes</td>
                        {% else %}
                            <td>No</td>
                        {% endif %}
                        <td>${{ room['cost_per_day'] }}</td>
                        <td>${{ room['cost_extra_bed'] }}</td>
                        {% if room['extra_bed'] == 1 %}
                            <td>${{ room['cost_extra_bed'] + room['cost_per_day'] }}</td>
                        {% else %}
                            <td>${{ room['cost_per_day'] }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="row">
            <div class="form-group row">
                <div class="text-left col-md-2">
                    <h4>Total Cost: ${{ total_cost }}</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group row">
                    <h4 class="col-md-3 text-left">Select Credit Card:</h4>
                    <div class="text-left col-md-2">
                        {{ form.credit_card(class_="form-control") }}
                    </div>
            </div>
        </div>
        <div class="row">
            <div class="row">
                <h4 class="col-md-4 text-left">Manage Credit Cards:</h4>
            </div>
            <div class="form-group row">
                <a role="button" class="btn" href={{ url_for('reservation_home_page_app.add_credit_card') }}>Add Credit Card</a>
                <a role="button" class="btn" href={{ url_for('reservation_home_page_app.delete_credit_card') }}>Delete Credit Card</a>
            </div>
        </div>
        <div class="row">

        </div>
        <div class="row">
            <div class="form-group row">
                <div class="text-left col-md-2">
                    {{ form.create_reservation(class_="btn btn-default right-align") }}
                </div>
            </div>
        </div>

        </form>
    </div>
{% endblock %}