models/reservations/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for, json
from models.reservations import ReservationWeb
from models.payment_information.payment_service import PaymentService
from models.forms.forms import CreateReservationPage1Form, CreateReservationPage2Form, AddPaymentInformationForm, \
    DeleteReservation, ConfirmReservationForm, UpdateWhichReservation, UpdateReservationDates, UpdateConfirm, \
    ProvideFeedback, ViewFeedbackChooseLocation, ReviewReservationForm, DeletePaymentInformationForm
from application import login_manager
from flask_login import login_required
from flask_login import current_user
from datetime import datetime
from datetime import timedelta
from datetime import date
import uuid
from models.rooms import room_service

reservation_home_page_app = Blueprint('reservation_home_page_app', __name__)
reservationweb = ReservationWeb()
payment_service = PaymentService()
roomservice = room_service.RoomService()


@reservation_home_page_app.route('/create-reservation', methods=['GET', 'POST'])
@login_required
def create_reservation():
    form = CreateReservationPage1Form(request.form)
    error = None
    location_list = reservationweb.get_locations()
    form.location.choices = [(location, location) for location in location_list]
    if request.method == 'POST':
        location = request.form.get('location')
        start_date = request.form.get('stdt')
        end_date = request.form.get('enddt')
        if start_date == '' or end_date == '':
            error = "You cannot leave the date fields blank"
        else:
            start_date = str(start_date)
            end_date = str(end_date)
            session['loc'] = location
            session['s_date'] = start_date
            session['e_date'] = end_date
            available_reservations = reservationweb.check_for_rooms(start_date, end_date, location)
            # add serialization: session['available_rooms'] = available_reservations
            if not available_reservations:
                error = "There are no available rooms that match your criteria"
            elif datetime.strptime(start_date, "%Y-%m-%d").date() <= date.today():
                error = "You must choose a date in the future"
            elif datetime.strptime(start_date, "%Y-%m-%d").date() >= datetime.strptime(end_date, "%Y-%m-%d").date():
                error = "You must choose a checkout date after the check in date"
            else:
                return redirect('/create-reservation-2')
    return render_template('create_reservation/create_reservation_page1.html', form=form, error=error)


@reservation_home_page_app.route('/create-reservation-2', methods=['GET', 'POST'])
@login_required
def create_reservation_page2():
    error = None
    all_selected_rooms_list = []
    start_date = session['s_date']
    end_date = session['e_date']
    location = session['loc']
    available_rooms = reservationweb.check_for_rooms(start_date, end_date, location)
    # s_rooms = available_rooms.__dict__
    # print s_rooms
    size = len(available_rooms)
    form = CreateReservationPage2Form(request.form)
    i = 0
    if request.method == 'POST':
        # rooms_selected = request.form.get('customer_room')
        rooms_selected = request.form.getlist('check')
        if len(rooms_selected) == 0:
            error = "You must select at least one room"
        else:
            for rs in rooms_selected:
                for room in available_rooms:
                    if rs == str(room.room_num):
                        # room_categories_numbers = {"room_number": room.room_num, "room_category": room.category}
                        all_selected_rooms = {'room_number': room.get_room_num(), 'category': room.get_category(),
                                              'persons_allowed': room.get_num_people(), 'cost_per_day': room.get_cost(),
                                              'cost_extra_bed': room.get_cost_extra_bed(), 'extra_bed': 0}
                        all_selected_rooms_list.append(all_selected_rooms)
            session['rooms'] = all_selected_rooms_list
            session['reservation_id'] = uuid.uuid4()
            return redirect(url_for('reservation_home_page_app.confirm_reservation'))
    return render_template('create_reservation/create_reservation_page2.html', form=form,
                           available_rooms=available_rooms,
                           location=location, error=error)


@reservation_home_page_app.route('/confirm-reservation', methods=['GET', 'POST'])
@login_required
def confirm_reservation():
    rooms = session['rooms']
    extra_beds_room_numbers = []
    form = ConfirmReservationForm(request.form)
    if request.method == 'POST':
        extra_beds = request.form.getlist('check')
        for bed in extra_beds:
            extra_beds_room_numbers.append(int(bed))
        i = 0
        j = 0
        while i < len(extra_beds_room_numbers):
            if extra_beds_room_numbers[i] == rooms[j]['room_number']:
                rooms[j]['extra_bed'] = 1
                j = 0
                i += 1
            else:
                j += 1
        if len(extra_beds_room_numbers) > 0:
            session['rooms'] = rooms
        return redirect(url_for('reservation_home_page_app.review_reservation'))
    return render_template('create_reservation/confirm_reservation.html', form=form, rooms=rooms)


@reservation_home_page_app.route('/review_reservation', methods=['GET', 'POST'])
@login_required
def review_reservation():
    error = None
    start_date = session['s_date']
    end_date = session['e_date']
    location = session['loc']
    rooms = session['rooms']
    reservation_id = session['reservation_id']
    credit_cards = payment_service.get_payment_information_by_username(current_user)
    form = ReviewReservationForm(request.form)
    form.credit_card.choices = [(cc.get_card_number(), cc.get_card_number()) for cc in credit_cards]
    total_cost = reservationweb.get_total_cost(rooms, start_date, end_date)
    print rooms
    if request.method == 'POST':
        credit_card_to_use = request.form.get('credit_card')
        if credit_card_to_use is None:
            error = "You must select or add a credit card"
        else:
            reservationweb.create(reservation_id, current_user, location, start_date, end_date, credit_card_to_use, rooms)
            return redirect('/')
    return render_template('create_reservation/review_reservation.html', form=form, reservation_id=reservation_id,
                           start_date=start_date, end_date=end_date, location=location, total_cost=total_cost,
                           rooms=rooms, error=error)


@reservation_home_page_app.route('/add-credit-card', methods=['GET', 'POST'])
@login_required
def add_credit_card():
    error = None
    form = AddPaymentInformationForm(request.form)
    if request.method == 'POST':
        card_number = request.form.get('card_number')
        card_exists = reservationweb.check_credit_card(card_number)
        name = request.form.get('name')
        expiration_date = request.form.get('expiration_date')
        cvv = request.form.get('cvv')
        if card_number == '' or name == '' or expiration_date == '' or cvv == '':
            error = "All fields must be completed"
        else:
            if card_exists is True:
                error = "The card number you have entered already exists."
            else:
                reservationweb.add_credit_card(name, card_number, expiration_date, cvv, current_user)
                return redirect(url_for('reservation_home_page_app.review_reservation'))
    return render_template('user/add_credit_card.html', form=form, error=error)


@reservation_home_page_app.route('/delete-credit-card', methods=['GET', 'POST'])
@login_required
def delete_credit_card():
    error = None
    form = DeletePaymentInformationForm(request.form)
    credit_cards = payment_service.get_payment_information_by_username(current_user)
    form.credit_card.choices = [(cc.get_card_number(), cc.get_card_number()) for cc in credit_cards]
    if request.method == 'POST':
        card_number = request.form.get('credit_card')
        can_delete = reservationweb.check_to_delete_credit_card(card_number)
        if can_delete is True:
            reservationweb.delete_credit_card(card_number)
            return redirect(url_for('reservation_home_page_app.review_reservation'))
        else:
            error = "You cannot delete a card that is being used by a reservation"
    return render_template('user/delete_credit_card.html', form=form, error=error)


@reservation_home_page_app.route('/customerreservationhome')
@login_required
def customer_home():
    reservations = reservationweb.get_reservations_by_username(current_user)
    return render_template('view_reservation/view_reservation.html', reservation_list=reservations)


@reservation_home_page_app.route('/delete-reservation', methods=['GET', 'POST', 'DELETE'])
@login_required
def delete_reservation():
    error = None
    message = None
    reservation_list = reservationweb.get_future_reservations(current_user)
    form = DeleteReservation(request.form)
    if request.method == 'POST':
        reservation_to_delete = request.form.getlist('reservation')
        if len(reservation_to_delete) > 1:
            error = "You can only select one reservation to delete"
        elif len(reservation_to_delete) == 0:
            error = "You must select a reservation to delete. If none are displayed, you do not have any reservations."
        elif len(reservation_to_delete) == 1:
            reservation_to_delete = reservation_to_delete[0]
            reservation = reservationweb.get_reservation_by_reservation_id(str(reservation_to_delete))
            if datetime.strptime(reservation.start_date, "%Y-%m-%d").date() <= date.today() + timedelta(days=1):
                message = "You have successfully deleted your reservation and will receive a 0% refund of $0"

models/user/views.py
from flask import Blueprint, render_template, request, json, redirect, session, url_for, request, flash
from marshmallow import *
from flask_restful import *
from models.forms.forms import LoginForm
from pip._vendor.requests import auth
from models.user.userweb import UserWeb
from models.forms.forms import LoginForm, SignUpForm
from flask_login import login_user, logout_user, current_user, login_required
from models.user.user import User

user_page_app = Blueprint('user_page_app', __name__)
userweb = UserWeb()


@user_page_app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
    if request.method == 'POST' and form.validate():
        username = request.form.get('username')
        password = request.form.get('password')
        user = userweb.login(username, password)
        if user is not None:
            user.is_active = True
            login_user(user, remember=False, force=False, fresh=True)
            flash('You have logged in successfully!')
            return redirect('/')
        else:
            error = "Login Unsuccessful. Please try again."
    return render_template("index/login.html", form=form, error=error)


@user_page_app.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignUpForm(request.form)
    error = None
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        password_verify = request.form.get('password_verify')
        error = userweb.validate_login_fields(username, email, password, password_verify)
        if error is None:
            (user, user_exists_error) = userweb.signup(username, password, email)
            if user is None:
                error = user_exists_error
            else:
                login_user(user)
                return redirect('/')
    return render_template("index/signup.html", form=form, error=error)


@user_page_app.route('/logout')
def logout():
    logout_user()
    return redirect('/')


@user_page_app.route('/')
def user_index():
    render_template("index/user_index.html")

templates/index/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
      {% block head %}
        <meta charset="utf-8"/>
        <title>Hotel Reservation</title>
        <link type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet">
          <link type="text/css" href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
          {{ moment.include_jquery() }}
        {{ moment.include_moment() }}
      {% endblock %}
  </head>

  <body>

    <div class="container">
      <div class="header">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                      <a class="navbar-brand" href="/">Hotel Reservation</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li role="presentation" class="active"><a href="/">Home</a></li>
                          {% if current_user.is_authenticated %}
                            <li role="presentation"><a href="{{ url_for('user_page_app.logout') }}">Log Out</a></li>
                          {% else %}
                              <li role="presentation"><a href="{{ url_for('user_page_app.login') }}">Log In</a></li>
                          {% endif %}
                      </ul>
                </div>
            </div>

        </nav>
      </div>
{% block content %}{% endblock %}


    </div>
  </body>
</html>

templates/index/login.html
{% extends "index/index.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/signin.css">
{% endblock %}

{% block content %}

    <div class="container">
            <form class="form-signin" action="" method="post" name="login">
                {{ form.hidden_tag }}
                {% if error %}
                    <h5 style="color:red;">Error: {{ error }} </h5>
                {% endif %}
                <h2 class="form-signin-heading">Log in</h2>
                  <div class="form-group">
                        {{ form.username(class_="form-control", placeholder="Username") }}
                  </div>
                <div class="form-group">
                    {{ form.password(class_="form-control", placeholder="Password") }}
                </div>
                    <p>{{ form.remember_me }} Remember Me</p>
                {{ form.sign_in(class_="btn btn-default") }}
                <div class="form-group ">
                    <a href="{{ url_for('user_page_app.signup') }}">New User? Sign up here!</a>
                </div>
          </form>

      </div>
{% endblock %}

templates/index/signup.html
{% extends "index/index.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/signin.css">
{% endblock %}

{% block content %}
    <div class="container">
        <form class="form-signin" action="" method="post" name="signup">
            {{ form.hidden_tag }}
            {% if error %}
             <h5 style="color:red;">Error: {{ error }} </h5>
            {% endif %}
            <h2 class="form-signin-heading">Sign Up</h2>
            <div class="form-group">
                {{ form.username(class_="form-control", placeholder="Username (C+name)") }}
            </div>
            <div class="form-group">
                {{ form.email(class_="form-control", placeholder="Email Address") }}
            </div>
            <div class="form-group">
                {{ form.password(class_="form-control", placeholder="Password") }}
            </div>
            <div class="form-group">
                {{ form.password_verify(class_="form-control", placeholder="Repeat Password") }}
            </div>
            <div class="checkbox">
              <label><input type="checkbox"> Remember me</label>
            </div>
            {{ form.sign_up(class_="btn btn-default") }}

            </form>
    </div>
{% endblock %}

templates/index/success_page.html
{% extends "index/index.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/style.css">
{% endblock %}

{% block content %}

    <div class="container user-index-padding">
        {% if message %}
            <h3 style="color:green;">{{ message }} </h3>
        {% endif %}
    </div>
{% endblock %}

templates/index/user_index.html
{% extends "index/index.html" %}
{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
    {% if current_user.is_authenticated %}
    <div ng-controller="UserIndexCtrl" class="container user-index-padding">
        <div class="row">
            <div class="col-md-3">
                <div class="btn-group-vertical">
                    <a role="button" class="btn btn-primary" href={{ url_for('reservation_home_page_app.create_reservation') }}>Make Reservation</a>
                    <a role="button" class="btn btn-primary" href={{ url_for('reservation_home_page_app.update_reservation') }}>Update a Reservation</a>
                    <a role="button" class="btn btn-primary" href={{ url_for('reservation_home_page_app.delete_reservation') }}>Cancel a Reservation</a>
                    <a role="button" class="btn btn-primary" href={{ url_for('reservation_home_page_app.provide_feedback') }}>Provide Feedback</a>
                    <a role="button" class="btn btn-primary" href={{ url_for('reservation_home_page_app.view_reviews_choose_location') }}>View Feedback</a>
                </div>
            </div>
            <div class="col-md-8">
                 <div class="jumbotron">
                    <div class="row">
                     <h2>Your Past, Current, and Future Reservations</h2>
                         <table class="table table-striped table-bordered table-condensed">
                            <tr>
                                <th>ReservationID</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Location</th>
                                <th>Total Cost</th>
                            </tr>
                            {% for reservation in reservation_list %}
                                {% if reservation['start_date'] <= today and reservation['end_date'] >= today %}
                                    <tr style="background:lightgreen;">
                                {% elif reservation['start_date'] < today and reservation['end_date'] < today %}
                                    <tr style="background:indianred;">
                                {% else %}
                                    <tr>
                                {% endif %}
                                        <td><a style="color:darkblue;" href={{ url_for('reservation_home_page_app.view_reservation', reservation_id=reservation.reservation_id) }}>{{ reservation.reservation_id }}</a></td>
                                        <td>{{ reservation['start_date']}}</td>
                                        <td>{{ reservation['end_date'] }}</td>
                                        <td>{{ reservation['location'] }}</td>
                                        <td>${{ reservation['total_cost'] }}</td>
                                    </tr>
                            {% endfor %}
                        </table>
                    </div>
                 </div>
            <p>The current date and time is: {{ moment().format('MMMM Do YYYY, h:mm:ss a') }}.</p>
            <p>Logged in as {{ current_user.username }}</p>
            </div>


        </div>
    </div>

    {% endif %}

{% endblock %}